# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57200f4330da9e788634969cfa3b4b05fffc7803605df784225cdeefdda7064419c5ed5eb9f9597100c9df3718859416567543b410068e2d4c51206e8c686591

test:
  secret_key_base: 140e1298c6aabcea2cc89aaa670698feb3ed90c5321851d553e13b4d8eaac3a26fd378ae3daece714db87c508436921027dabdc2f5cf905d11ddc8d3574be7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
